# Generated by Django 5.0.6 on 2024-11-11 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Profile',
                    fields=[
                        ('id', models.AutoField(auto_created=True,
                                                primary_key=True, serialize=False, verbose_name='ID')),
                        ('favorite_city', models.CharField(
                            blank=True, max_length=64)),
                        ('user', models.OneToOneField(
                            on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'oc_lettings_site_profile',
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
