# Generated by Django 3.0 on 2024-10-11 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrate_profiles_data(apps, schema_editor):
    OldProfile = apps.get_model('oc_lettings_site', 'Profile')  # Ancien modèle
    NewProfile = apps.get_model('profiles', 'Profile')  # Nouveau modèle

    for old_profile in OldProfile.objects.all():
        NewProfile.objects.create(
            user=old_profile.user,
            favorite_city=old_profile.favorite_city,
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_city', models.CharField(blank=True, max_length=64)),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(migrate_profiles_data),
    ]
