# Generated by Django 3.0 on 2024-10-11 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0003_auto_20241011_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'adresse', 'verbose_name_plural': 'adresses'},
        ),
    ]
